### ISSUE TITLE
visHierarchicalLayout performance 

### ISSUE THREAD

**Issue by robbig2871** [DataKnowledge/visNetwork#1]
Hi ,

Example as below is working OK at R preview and WebBrowser:
```{r}
nodes <- data.frame(id = 1:500)
edges <- data.frame(from = c(1,2), to = c(1,3))
visNetwork(nodes, edges)
network <-  visNetwork(nodes, edges)
htmlwidgets::saveWidget(network, "network.html")
```

when I am trying visHierarchicalLayout it is working in R preview but hungs with WebBrowser.

```{r}
nodes <- data.frame(id = 1:500)
edges <- data.frame(from = c(1,2), to = c(1,3))
network <- visNetwork(nodes, edges, width = "100%") %>% visEdges(style = "arrow") %>%  visHierarchicalLayout(layout = "direction")
htmlwidgets::saveWidget(network, "network.html")
```

Firefox Java Console log shows (chrome and safari has similar issue):
![screen shot 2015-05-04 at 12 14 06 am](https://cloud.githubusercontent.com/assets/3903647/7447205/81cf8b4e-f1f2-11e4-9beb-9805bf34dd01.png)

**Comment by bthieurmel** [comment]
Hi,
I think your example is a little bit strange for me..., so can I first ask you why do you want to draw a hierarchical network with 500 nodes, and only 2 edges ?
It seems that vis.js use an algorithm to determine level of each node, and repulsion using hierarchical layout. 
You can perhaps try : 
 - fix level of nodes before, by adding a numeric 'level" column to nodes, from 0 to n 
````
nodes <- data.frame(id = 1:5, level = c(0,0,1,1,2))
edges <- data.frame(from = c(1), to = c(2))
visNetwork(nodes, edges) %>% visHierarchicalLayout()
````
- trying to disable repulsion, playing with physics, for example : 
````
visNetwork(nodes, edges) %>% visHierarchicalLayout()%>% 
  visPhysics(hierarchicalRepulsion = list(damping = 1))
````
