### ISSUE TITLE
More documentation on visPhysics?

### ISSUE THREAD

**Issue by happyshows** [DataKnowledge/visNetwork#10]
Hi,

Could you provide more documentations on how to adjust the forces? Thanks.

**Comment by bthieurmel** [comment]
Hi, 

All vis.js documentation is available using ````?visPhysics```` or ````visDocumentation````, but it's true than some examples can be relevant.
To test physics, you can look at : 
- http://visjs.org/examples/network/physics/physicsConfiguration.html
- http://visjs.org/examples/network/other/configuration.html
- ore use directly ````visConfigure```` on your network in R, and open it in a browser to play with configuration

**Comment by happyshows** [comment]
thanks.
