### ISSUE TITLE
Missing legend for latest Dev version.

### ISSUE THREAD

**Issue by happyshows** [DataKnowledge/visNetwork#11]
The following code didn't work - not able to see the legend. Nor my own data worked.
set.seed(123)
nodes <- data.frame(id = 1:10, color = c(rep("blue", 6), rep("red", 3), rep("green", 1)))
edges <- data.frame(from = round(runif(6)*10), to = round(runif(6)*10))
visNetwork(nodes, edges, legend = TRUE)

![untitled](https://cloud.githubusercontent.com/assets/3208181/8537314/ecadfb46-2422-11e5-878c-668e43b025ce.png)

**Comment by happyshows** [comment]
R version 3.1.2 (2014-10-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)

locale:
[1] LC_COLLATE=English_United States.1252 
[2] LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] visNetwork_0.0.4          ADAP.Util_0.2.3          
[3] formattable_0.0.15.2      tidyr_0.2.0              
[5] dplyr_0.4.2.9000          shinydashboard_0.5.0.9000
[7] shinyBS_0.61              igraph_0.7.999-125       

loaded via a namespace (and not attached):
 [1] assertthat_0.1    DBI_0.3.1         digest_0.6.4     
 [4] evaluate_0.5.5    formatR_1.0       htmltools_0.2.7  
 [7] htmlwidgets_0.5   httpuv_1.3.2      jsonlite_0.9.16  
[10] knitr_1.7         lazyeval_0.1.10   magrittr_1.0.1   
[13] markdown_0.7.4    mime_0.3          parallel_3.1.2   
[16] R6_2.0.1          Rcpp_0.11.6       rJava_0.9-6      
[19] RJDBC_0.2-4       rjson_0.2.14      RSQLite_1.0.0    
[22] rstudioapi_0.2    shiny_0.12.0.9002 stringi_0.4-1    
[25] stringr_1.0.0     tools_3.1.2       xtable_1.7-4     
[28] yaml_2.1.13

**Comment by bthieurmel** [comment]
Hi, 
As help says, legend can only be used in case of groups. For example : 
````
set.seed(123)
nodes <- data.frame(id = 1:10, group = c(rep("A", 6), rep("B", 3), rep("C", 1)))
edges <- data.frame(from = round(runif(6)*10), to = round(runif(6)*10))
visNetwork(nodes, edges, legend = TRUE) %>%
  visGroups(groupname = "A", color = "blue") %>%
  visGroups(groupname = "B", color = "red") %>%
  visGroups(groupname = "C", color = "green")
````

**Comment by happyshows** [comment]
if I have 20 unique values in group, do I have to specify line by line like the example you gave above? What if the groupnames are variable?
Currently, my dataset utilizes color = colorvector directly, also I don't know how many groups I have because the slicing of source data keep changing. (visNetwork + shiny) It there a better way to handle such use case?

**Comment by happyshows** [comment]
I suggest the following two chunks should yield same result:

nodes <- data.frame(id = 1:10, group = c(rep("A", 6), rep("B", 3), rep("C", 1)),
                    color = c(rep("blue", 6), rep("red", 3), rep("green", 1)))
edges <- data.frame(from = round(runif(6)*10), to = round(runif(6)*10))
visNetwork(nodes, edges, legend = TRUE)


nodes <- data.frame(id = 1:10, group = c(rep("A", 6), rep("B", 3), rep("C", 1)),
                    color = c(rep("blue", 6), rep("red", 3), rep("green", 1)))
edges <- data.frame(from = round(runif(6)*10), to = round(runif(6)*10))
visNetwork(nodes, edges, legend = TRUE) %>%
  visGroups(groupname = "A", color = "blue") %>%
  visGroups(groupname = "B", color = "red") %>%
  visGroups(groupname = "C", color = "green")

**Comment by bthieurmel** [comment]
Yes, but the nodes/groups system is a little bit complex.
- you can share properties between nodes using groups configuration, and ```` visGroups````
- but all nodes can have there own properties using ````visNodes````

The legend looks actually only the groups properties. We don't look on groups properties, and on nodes informations, and try to find some global groups properties defined per node.

For several groups, you can still use a loop / apply function : 
````
nodes <- data.frame(id = 1:10, group = c(rep("A", 6), rep("B", 3), rep("C", 1)),
   color = c(rep("blue", 6), rep("red", 3), rep("green", 1)))

edges <- data.frame(from = round(runif(6)*10), to = round(runif(6)*10))

network <- visNetwork(nodes, edges, legend = TRUE)

groups <- c("A", "B", "C")
colors <- c("blue", "red", "green")

for(gr in 1:length(groups )){
   network <- visGroups(network , groupname = groups[gr], color = colors[gr]) 
}
network
````

**Comment by happyshows** [comment]
thanks. it seems to be tedious to use. Is it because of the way visjs works?

**Comment by bthieurmel** [comment]
Yes. vis.js don't propose an API to add legend. I try to propose (quickly...) a first legend functionnality based on groups.
A more custom legend function is in reflexion in the next step.

**Comment by HermanSontrop** [comment]
hi,

just a thought, but it would also be very useful when you use images as nodes to have a legend reflect that, instead of just using colors and shapes. Don't know how hard it would be, but it would basically be a list of divs holding the unique images in the nodes (assuming there are not too many), with perhaps a set of small text strings below each image.

best H

**Comment by happyshows** [comment]
just a follow up idea, 
maybe icons instead of custom images?
http://fontawesome.io/icons/
http://getbootstrap.com/components/#glyphicons

it's more standardized and used by many packages including shinydashboard.

**Comment by bthieurmel** [comment]
Before trying to build a custom legend, you can now use fontawesome icons using visNodes and visGroups function.
It's actually only on the github master version 0.1.1. You can try if you want. Have a look to ````?addFontAwesome````

**Comment by happyshows** [comment]
@bthieurmel just tried earlier, this is a great feature. thanks.

**Comment by happyshows** [comment]
@bthieurmel  question about the code variable, how to translate the icon on http://fortawesome.github.io/Font-Awesome/icons/  to "code" ?

**Comment by bthieurmel** [comment]
You can click on an icon on page http://fortawesome.github.io/Font-Awesome/icons/ for see his unicode, or look at the http://fortawesome.github.io/Font-Awesome/cheatsheet/ and taking the fourth f.... ( f195 for ````[&#xf195;]````)

**Comment by happyshows** [comment]
cool thanks.

**Comment by bthieurmel** [comment]
Just for information (and for tests if you want), a new function ````visLegend```` is available (on github actually).

- add custom nodes / edges on legend

**Comment by happyshows** [comment]
thanks will check
