### ISSUE TITLE
[improvement idea] Temporal Network Capability?

### ISSUE THREAD

**Issue by happyshows** [DataKnowledge/visNetwork#13]
Here's my use case (in supply chain):
Parts move from different place/stages in a weekly manner.
I used quarterly data (distinct edge relationship) to build the skeleton of the network.
Then at particular week fill in different color on the edge to indicate weekly volumn data (some edge might be none, which should be transparent)
However, the issue is if I update with a new dataset, the diagram will redraw and the position of node become random.

Is there a way to include a version component and able to 'play' the network while keeping all nodes/edges in their original position?

**Comment by bthieurmel** [comment]
With same data, you can have same network using ````randomSeed````

````
nodes <- data.frame(id = 1:10)
edges <- data.frame(from = round(runif(8)*10), to = round(runif(8)*10))

visNetwork(nodes, edges) %>%
 visLayout(randomSeed = 123)
````

Adding new nodes/edges, you can perhaps try to define ````x```` and ````y```` position to nodes...

**Comment by bthieurmel** [comment]
If you know all your data before to start, you can also use ```hidden``` options available for nodes and edges, and set a randomSeed.

**Comment by happyshows** [comment]
@bthieurmel I don't quite get this 'hidden' suggestion. Does it turn off all nodes/edges entirely? I was thinking of per Node/Edge level control by version.

**Comment by happyshows** [comment]
also can you provide an example on fixing x, y position based on data frame value? thanks..

**Comment by bthieurmel** [comment]
Concerning ````hidden```` options, it's a per node/edge options : 

````
nodes <- data.frame(id = 1:3, hidden = c(FALSE, FALSE, TRUE))
edges <- data.frame(from = c(1,2), to = c(1,3), hidden = c(FALSE, TRUE))

visNetwork(nodes, edges) %>% visLayout(randomSeed = 123) %>%
  visPhysics(stabilization = TRUE)

nodes <- data.frame(id = 1:3, hidden = c(FALSE, FALSE, FALSE))
edges <- data.frame(from = c(1,2), to = c(1,3), hidden = c(FALSE, FALSE))


visNetwork(nodes, edges) %>% visLayout(randomSeed = 123) %>%
  visPhysics(stabilization = TRUE)
````

**Comment by bthieurmel** [comment]
And this is an example using ````x```` and ````y```` position : 
````
nodes <- data.frame(id = 1:3, x = c(0,100,-100), y = c(100,0,0), label = 1:3)
edges <- data.frame(from = c(1,2), to = c(1,3))

visNetwork(nodes, edges) %>%
  visNodes(fixed = TRUE)
````

**Comment by happyshows** [comment]
@bthieurmel  this should be a workaround for me, will let you know when I have more ideas.
