### ISSUE TITLE
Is there a way visDataSet could be added

### ISSUE THREAD

**Issue by dockstreet** [DataKnowledge/visNetwork#14]
Hi!

I would like to be able to refer to nodeValues. Can the below be addressed? thx!

https://github.com/almende/vis/issues/1178

**Comment by bthieurmel** [comment]
Can you give more details of what you want to do ?

**Comment by dockstreet** [comment]
What I would like to do is pass a node value to a URL instead of a node Id in javascript on a click event.

**Comment by bthieurmel** [comment]
Something like that seems to work for me : 

````
`
nodes <- data.frame(id = 1:3, value = c(10, 20, 30))
edges <- data.frame(from = c(1,2), to = c(1,3))

visNetwork(nodes, edges) %>%
  visEvents(click = "function(properties) {
      console.info(this);
      alert('selected nodes: ' + this.body.data.nodes.get(properties.nodes[0]).value);}")

````

**Comment by dockstreet** [comment]
Excellent ! thank you sooooo much!
