### ISSUE TITLE
Geographic coordinates and map overlay

### ISSUE THREAD

**Issue by benizar** [DataKnowledge/visNetwork#15]
Dear developers,

First, thank you for this great package.

I want to plot 2D graphs using geographic coordinates for the nodes. I think that this is possible with visNetwork. However, I don't see a way I could use a georreferenced map as **background**. Is there any option I could use (vis or html)?

As for example, take a look at this similar question on the iGraph package: 
 - http://stackoverflow.com/questions/30647537/using-geo-coordinates-as-vertex-coordinates-in-the-igraph-r-package

Thank you in advance for your attention.

Beni.

**Comment by bthieurmel** [comment]
Hi,

Actually, I don't think there is an option, or a quite simple way to do this using vis.js and visNetwork....

**Comment by benizar** [comment]
Thank you very much for answering.

I have been reading some code and it seems very complicated. Thus, I have decided that is easier for me to write some routines to export the visNetwork graphs to GIS and importing back the edited network... I will share what I achieve in a couple of gists.

Thank you again ;)
