### ISSUE TITLE
how to set different width for each edge?

### ISSUE THREAD

**Issue by zhiboz** [DataKnowledge/visNetwork#16]
great network visualization tool! just wonder if it is possible to set different width for each edge; looked through the doc but was only able to set a global edge width.

**Comment by bthieurmel** [comment]
Hi,
It's possible using the __value__ argument : 

````
nodes <- data.frame(id = 1:3)
edges <- data.frame(from = c(1,2), to = c(1,3), value = c(1, 10))

visNetwork(nodes, edges)
````

**Comment by zhiboz** [comment]
It works! I tried the *width* attribute but it did not work. Thanks very much!

**Comment by dkgaraujo** [comment]
Would be great if the documentation reflected this more clearly.
