### ISSUE TITLE
fontawesome legend does not resize correctly in shiny mode

### ISSUE THREAD

**Issue by happyshows** [DataKnowledge/visNetwork#17]
Hi,

It seems to be relative okay on Rstudio viewer but is missing one legend and overlaps badly on shiny mode, could you take a look? 

Appreciate the good work!

**Comment by happyshows** [comment]
![untitled](https://cloud.githubusercontent.com/assets/3208181/9794175/448211d0-57af-11e5-969e-5dc0abb41cb0.png)

**Comment by happyshows** [comment]
I'd suggest ignore the size parameter in legend section and resize automatically based on the # of groups?

**Comment by bthieurmel** [comment]
Hi,

It'seems is not a font awesome bug, but a more global problem. In case of several network in a shiny app, only one resize....
If I put only one network, with font awesome, it's good for me. Can you confirm it's good for you too in this case ?
I'll look at this....

**Comment by bthieurmel** [comment]
I've just update the master branch, Can you try ?

**Comment by happyshows** [comment]
I did reinstall the package, but the problem still exists
![untitled](https://cloud.githubusercontent.com/assets/3208181/9806046/909982aa-5805-11e5-8044-4519e81b9b66.png)

**Comment by bthieurmel** [comment]
OK, I miss-understand the problem first. I now fix the icon size in legend to default value.
You can try.

**Comment by happyshows** [comment]
confirmed.
