### ISSUE TITLE
How to make directed-graph in data manipulating feature

### ISSUE THREAD

**Issue by ThoDuyNguyen** [DataKnowledge/visNetwork#18]
Hello everyone 

Data manipulating is a great feature but it seems that it only support indirect graph even though our original graph is directed. 

Could we have any solution/workaround for this?

**Comment by bthieurmel** [comment]
Hi,

Can you explain a little bit more what you need ?

On basic example, manipulation seems to work with directed graph : 

````
nodes <- data.frame(id = 1:15, label = paste("Label", 1:15),
                    group = sample(LETTERS[1:3], 15, replace = TRUE))

edges <- data.frame(from = trunc(runif(15)*(15-1))+1,
                    to = trunc(runif(15)*(15-1))+1)


# directed network
visNetwork(nodes, edges) %>%
  visEdges(arrow = 'from', scaling = list(min = 2, max = 2)) %>% 
  visOptions(manipulation = TRUE)
````

Perhaps, you think about more options editing data (arrow ?).

**Comment by ThoDuyNguyen** [comment]
Hi bthieurmel 

I update the library and it seems that new version fix my problem. 

Thank you for your response. 

The case could be closed now

**Comment by bthieurmel** [comment]
Ok, cool !
