### ISSUE TITLE
How to send back graph changes done in manipulation mode

### ISSUE THREAD

**Issue by hnbeck** [DataKnowledge/visNetwork#19]
If the graph is manipulated via manipulation mode (vis.js level), nodes added or deleted or node data changed, how can these changes send back to R level such that nodes and edges data frames contain this changes ? I changed some graphs graphically, but the node and edges data frames keep always unchanged.

**Comment by smartinsightsfromdata** [comment]
@bthieurmel  I comment on this on the basis of my (limited) experience of  htmlwidgets developer, as well as as a keen user of this great widget.

A possible example of these types of implementations is rhandsontable (now on CRAN), developed by @rjowen. There there is a function to get the data back from the table whenever there is a table change in the UI side.  

This is usually done with a callBack on the javascript side and Shiny.onInputChange.

Typically the entire dataset is sent back (there are ways to avoid this but are quite complex and error prone) to the server, which should be acceptable in most usecases.

**Comment by hnbeck** [comment]
Thanks for your quick respond !. But forgive me, I don't understand in full extend. But I will look at the example you told me. I think it would be useful in general if data could not only be visualized with the great shiny stuff but also changed such that this changes can be processed further in R.

**Comment by hnbeck** [comment]
I*ve forked now visNetwork in order to implement the feed back of changes in the network done in vis.js back to R. Another point I'll try is to show and edit more data fields of a node, if this  would be possible without changes in vis.js
