### ISSUE TITLE
dynamic network

### ISSUE THREAD

**Issue by Artagen** [DataKnowledge/visNetwork#2]
Hi. 
Thanks for the great package !
I'm using shiny and i was asking if it is possible to build dynamic network "programmatically" 
- i mean as the user can edit the network for example, would it be possible to do the same, but based on some "script" send by the server file ?
- idea is to see "clips" of network dynamic : nodes coloring one after the other (to see flow of information), network growing in size, ...

Thanks in advance for the support !

Regards,

Pierre

**Comment by bthieurmel** [comment]
Hi,

Actually, there is not proper way to do this. In futur, we can perhaps think about passing several nodes and edges data.frame, and use setData() and redraw() method in javascript code....

Now, you can perhaps try  : 

````
require(shiny)
require(visNetwork)

ui <- shinyUI(bootstrapPage(
  sliderInput("col", NULL, 1, 8, 1, step = 1, animate = TRUE),
  visNetworkOutput("network",height = "600px")
))

server <- shinyServer(function(input, output, session) {
  
   data <- reactive({
      data.frame(id = 1:3, y = c(-100,0,100), x = c(100,200,300), color = palette()[input$col]) 
   })
   
  output$network <- renderVisNetwork({
      nodes <- data()
      edges <- data.frame(from = c(1,2), to = c(1,3))
      visNetwork(nodes, edges) %>%
        visOptions(stabilize = FALSE, zoomable = FALSE, dragNetwork = FALSE, 
                   smoothCurves = list(dynamic = FALSE, type= "continuous"))
    })
})

runApp(list(
    ui=ui,
    server=server
))
````
The coordinates of nodes are fixed, and the network stabilized. So we cant just change some properties on data, and update network....
 
In the last package version, another feature have been added for shiny. Using  nodesIdSelection options, you have a new input (input$networkid_selected) with the current value of the selected node.
Can try with runApp(system.file("shiny", package = "visNetwork")), after updating package of needed.

**Comment by Artagen** [comment]
Hi.

Thanks for your help  I'll try your proposal.
Meanwhile, i found another way, but then by directly using vis.js and using javascript code directly inside my shinyApp, but i found this rather complex and not easy to handle...

Also, thank you for the update regarding the selected node, i will be quite useful for the app i'm currently working on...

**Comment by Artagen** [comment]
Hello.

First, thanks again for all your great work !

i got a question regarding your code to simulate node color changing dynamically : it works nice indeed, but an annoying thing is that every time the network is redraw (ie every time the slider input change value), the height of the web page increase (ie it is like the new redraw is "stacked" on top of previous one, even if one see only the last redraw). 

Is there a way to prevent this "stacking" behaviour ?

**Comment by bthieurmel** [comment]
Can you try re-install visNetwork ? Normally, I fixes that a few days ago.

**Comment by Artagen** [comment]
Great ! This work perfect now. Thank you a lot !
