### ISSUE TITLE
[Enhancement] Allow to specify which node/group/edge is selected when graph is loaded

### ISSUE THREAD

**Issue by happyshows** [DataKnowledge/visNetwork#23]
Hi,

I use visNetwork almost exclusively with shiny, there are cases I want the graph to be preloaded with calculated result so the end user will see a problem (highlighted) immediately.
Can this be incorporated in next release?

Thanks.

**Comment by ThoDuyNguyen** [comment]
It would be nice feature

**Comment by bthieurmel** [comment]
Hi,
Using a default value on ````nodesIdSelection```` or  ````selectedBy```` ca

**Comment by bthieurmel** [comment]
Done with a possible default value on ````nodesIdSelection```` or ````selectedBy````.
Can test on github version. Have a look to ````visOptions```` documentation.

**Comment by happyshows** [comment]
looks good to me.
