### ISSUE TITLE
[question] Can someone explain the degree option in highlightNearest function?

### ISSUE THREAD

**Issue by happyshows** [DataKnowledge/visNetwork#25]
Hi,

I tried to put different values in degree parameter and the highlighted nodes seems to be the same. Can you explain how it works? and if possible please provide a minimal example on how to utilize it.
Also, will the degree be directional? meaning highlight the parent nodes or child nodes only? This could help when we need to trace some flow.

Thanks

**Comment by bthieurmel** [comment]
Hi,
````degree```` control the number of level of nodes we highlight : 
- degree = 0, only selected node is highlighted 
- degree = 1, selected node & first linked nodes are highlighted
- ... 

````degree```` is not really directional (javascript method return connected nodes, wtihout direction), but the edges are drawn if they begin from last nodes level...

Here is an example to show : 

````
# minimal example
nodes <- data.frame(id = 1:14, label = 1:14, group = LETTERS[1:7])
edges <- data.frame(from = c(1,1,4,5, 4, 5, 6, 7, 8, 9, 10, 11), 
                    to = c(2, 3, 1, 1, 8, 9, 2, 3, 12, 13, 6, 7))

# default, on group
visNetwork(nodes, edges) %>%
  visEdges(arrows = "to") %>%
  visOptions(highlightNearest = list(enabled = TRUE, degree = 0))
  
visNetwork(nodes, edges) %>%
  visEdges(arrows = "to") %>%
  visOptions(highlightNearest = list(enabled = TRUE, degree = 1))

visNetwork(nodes, edges) %>%
  visEdges(arrows = "to") %>%
  visOptions(highlightNearest = list(enabled = TRUE, degree = 2))
````

**Comment by happyshows** [comment]
k thanks.
