### ISSUE TITLE
How to customize elements like background, border, and opacity for individual nodes/edges?

### ISSUE THREAD

**Issue by thercast** [DataKnowledge/visNetwork#26]
Hello, first I want to say thank you for creating such an innovative package for visualizing networks!  For some of my graphs I'd like to have some nodes have different background colors than others, and also be able to customize other aspects like the border.  Same concept for edges: I'd like to set for example the opacity of one edge to be smaller than others.  When I define the data frame with node information, it's easy to set the color for the node as a separate column, but when I try to add the individual attributes like background and border, there is no effect when I render the graph.  I know that the documentation for `visNodes` says to supply a named list containing the desired values for say background and border, but as far as I can tell this applies the settings to all nodes.  Is there a way to specify these types of attributes on a per-node basis?  Here's some example code I tried.  I'm running the latest version from CRAN.

```r
library(visNetwork)
library(magrittr)

nodes <- data.frame(id = paste0("node", 1:5),
                    label = paste0("node", 1:5),
                    shape = "box",
                    background = c("green", "yellow", "yellow", "red", "red"),
                    border = "black")

edges <- data.frame(
  from = c("node1", "node2", "node2", "node3", "node4", "node5"),
  to = c("node2", "node3", "node5", "node4", "node5", "node4"),
  label = paste0("edge", 1:6),
  length = 400,
  smooth = TRUE,
  color = c("red", "blue", "blue", "blue", "blue", "blue"),
  opacity = c(0.1, 0.1, 1, 1, 1, 1))

visNetwork(nodes, edges) %>%
  visEdges(arrows = "to", font = list(background = "white", size = 16)) %>%
  visLayout(randomSeed = 7, hierarchical = FALSE, improvedLayout = TRUE)
```

**Comment by bthieurmel** [comment]
Hi, 
Just a quick answer : 
- for nodes, you can set custom options using ````group```` column and after ````visGroups```` function. Here is an example : 
````
nodes <- data.frame(id = 1:10, label = paste("Label", 1:10),
                    group = sample(c("A", "B"), 10, replace = TRUE))
edges <- data.frame(from = c(2,5,10), to = c(1,2,10))

visNetwork(nodes, edges) %>%
  visGroups(groupname = "A", , shape = "database",
            color = list(background = "red", border = "orange", highlight = "yellow")) %>%
  visGroups(groupname = "B", , shape = "triangle",
            color = list(background = "blue", border = "green", highlight = "purple"))
````
- for edges, i think it's actually not possible, but perhaps in the futur, using list of list rather than data.frame...

**Comment by thercast** [comment]
Thank you @bthieurmel !  I was able to use your solution to format the node attributes differently by group, and that's sufficient enough for now.  Eventually it would be great to do the same customization for the edges either incoming or outgoing based on group membership, but it's not a critical issue right now.

**Comment by bthieurmel** [comment]
For information, i've just update visNetwork on github to have the possibility to pass custom "list" options directly using data.frame. This is an example : 

````
nodes <- data.frame(id = 1:3, 
 color.background = c("red", "blue", "green"),
 color.highlight.background = c("red", NA, "red"), 
 shadow.size = c(5, 10, 15))

edges <- data.frame(from = c(1,2), to = c(1,3),
 label = LETTERS[1:2], 
 font.color =c ("red", "blue"), 
 font.size = c(10,20))

visNetwork(nodes, edges)
````

You just have to keep the notation, same as list, but separate by point.
