### ISSUE TITLE
[Enhancement] More features in selectedBy | Nodeselection

### ISSUE THREAD

**Issue by happyshows** [DataKnowledge/visNetwork#27]
Hi,

Firstly, thanks for the quick implementation on default values.
I'm wondering can the dropdown list be further customized?

1) filter some unwanted nodes, there's a huge amount of nodes but I only want user to choose from a given list. for example, nodes ends with '_FG$' this will help remove the noises
2) able to sort the drop down list option items
3) make the width of drop down configurable OR wider to accommodate long character string

Thanks

**Comment by bthieurmel** [comment]
Hi,

I've already think about some more features on ````selectedBy```` & ````nodesIdSelection```` like control width for example.
Coming soon...

**Comment by bthieurmel** [comment]
Add HTML ````style```` configurable for ````selectedBy```` and ````nodesIdSelection```` today.

And I'll add the possibility to enter values we want in list in the next days.

**Comment by bthieurmel** [comment]
And now add ````values```` for subset on data for ````selectedBy```` and ````nodesIdSelection```` today.

So you can test !
