### ISSUE TITLE
[Question] is there any update on the algorithm behind visHierarchicalLayout for v 0.2.0?

### ISSUE THREAD

**Issue by happyshows** [DataKnowledge/visNetwork#29]
Hi,

it seems my model can no longer visualize the visHierarchicalLayout correctly after I upgraded to 0.2.0.
I'm wondering if this is due to the upgrade or something else happened at a vis.js level?

thanks..

**Comment by bthieurmel** [comment]
on history of vis.js, they says for 4.10 : 

- Fixed #1343: Connected edges are now deselected too when deselecting a node.
- Fixed #1398: Support nodes start with the correct positions.
- Fixed #1324: Labels now scale again.
- Fixed #1362: Layout of hierarchicaly systems no longer overlaps NODES.
- Fixed #1414: Fixed color references for nodes and edges.
- Fixed #1408: Unclustering without release function respects fixed positions now.
- Fixed #1358: Fixed example for clustering on zoom.
- Fixed #1416: Fixed error in improvedLayout.
- Improvements on hierarchical layout.

in `R`, I don't change code for layout, and simple network seems to be ok. Can you have any error in a Javascript and/or send me a reproductible example ?

**Comment by happyshows** [comment]
Could you leave your email so that I can forward you the rda (vis object) to you?

The only error I can find it below:
vis.js:38194Uncaught TypeError: Cannot read property 'amount' of undefined

**Comment by bthieurmel** [comment]
My email : bthieurmel@gmail.com. I'll have a look tomorrow

**Comment by bthieurmel** [comment]
I've just update to vis.js 4.11.0. It seems to be ok.... (but we don't have a answer for the initial problem...)

**Comment by happyshows** [comment]
Confirmed, I'll reopen this ticket if in future it occurs again.
