### ISSUE TITLE
plans for release

### ISSUE THREAD

**Issue by timelyportfolio** [DataKnowledge/visNetwork#3]
You have done a really nice job with this package.  I'd like to feature it on my site http://buildingwidgets.com, but I don't want to jump the gun.  I had assumed since you posted to your blog that you consider it ready for public consumption.  I just wanted to verify before writing it up.

Again, well done with this.

**Comment by bthieurmel** [comment]
Hi,
You made a good supposition. It is exactly developed for people can use it!. 
For information, and for the distribution of package, I tried to connect our (little) blog to r-blogger, without news for the moment, and I am going to try a CRAN submission soon.
So I can only thank you also if you made a little publicity.

**Comment by timelyportfolio** [comment]
Great, I'll start small with https://twitter.com/timelyportfolio/status/601416891417161728.  I will mention in a post this week, and then hopefully can work up a post just on `visNetwork`.

**Comment by timelyportfolio** [comment]
Also, let me know how can I help.

**Comment by bthieurmel** [comment]
Thank you ! It seems that you are better than me for the communication...

For R-bloggers, I 'll make a second attempt, adding before new article on our blog (perhaps on other vis3D package), otherwise, too bad for me.

**Comment by bthieurmel** [comment]
I'm really not a javascript coder, so javascript code is a perhpas a little bit dirty. I'll try to do some cleanup before first cran submission.

You're welcome for any proposal / improvement If  time and motivation are there.

**Comment by timelyportfolio** [comment]
also posted on Google+ https://plus.google.com/+KentonRussell/posts/M9ye3V9tBWs

**Comment by timelyportfolio** [comment]
This [post](http://timelyportfolio.blogspot.com/2015/05/visnetwork-currencies-and-minimum.html) should get on r-bloggers.
