### ISSUE TITLE
[Enhancement] ways to decrease plotting speed

### ISSUE THREAD

**Issue by Tixierae** [DataKnowledge/visNetwork#32]
It takes very long (about one minute both on shinyapps.io and RStudio on my laptop) to plot a graph with only 140 nodes/250 edges, and my browser freezes/almost collapses. Is that normal? What are ways to optimize performance?

Note: I know that `hideEdgesOnDrag` and `hideNodesOnDrag` can help once the graph is plotted, but here my problem deals with the time required to plot the graph initially.

Thanks in advance for your advice

**Comment by bthieurmel** [comment]
Hi, 

Can you send me a reproductible example / some data to look at your question ?

**Comment by Tixierae** [comment]
`library("igraph")
library("visNetwork")
set.seed(1234)
# create random graph with 140 nodes and 250 edges
g = erdos.renyi.game(140,250,type="gnm")
V(g)$id = 1:140
g_data_frame = get.data.frame(g, what="both")
visNetwork(g_data_frame$vertices, g_data_frame$edges)`

Takes ~40 seconds on my laptop and Amazon EC2 micro instance.

**Comment by bthieurmel** [comment]
First, you can disable stabilization before rendering like this : 

``
visNetwork(g_data_frame$vertices, g_data_frame$edges) %>%
  visPhysics(stabilization = FALSE)
``
By default, vis.js try to stabilize network before plotting

**Comment by bthieurmel** [comment]
Another tips is to disabled smooth curve for edges. It's better for performance : 

``
visNetwork(g_data_frame$vertices, g_data_frame$edges) %>%
  visPhysics(stabilization = FALSE) %>%
  visEdges(smooth = FALSE)
``
And play with the visPhysics options for control the stabilization process

**Comment by bthieurmel** [comment]
And, if you can / if you draw same network several time, you can pass x & y coordinate to nodes data.frame....

**Comment by Tixierae** [comment]
Many thanks for the prompt feedback. This has decreased the plotting speed to about 11 seconds. Do you have any other suggestion?

**Comment by Tixierae** [comment]
OK thanks. I guess the coordinates are returned by the `visPhysics` function. Do you know how to access and save them for later re-use? (it seems that the function does not return anything explicitly).

**Comment by bthieurmel** [comment]
This feature is in progress...! And I think you can only do this using shiny.

With the actual version on github (add this in the last minute...!), youcan use ``visNetworkProxy`` & ``visGetPositions`` to get positions after stabilization. This is an example : 

````
require(shiny)
require(visNetwork)

server <- function(input, output) {

  output$network <- renderVisNetwork({
    nodes <- data.frame(id = 1:3)
    edges <- data.frame(from = c(1,2), to = c(1,3))
    
    visNetwork(nodes, edges) %>% visNodes(color = "green")
  })
  
  output$test <- renderPrint({
    input$network_positions
  })
  observe({
    input$goButton
    visNetworkProxy("network") %>%
      visGetPositions(nodes = c(1, 2))
  })
  
}

ui <- fluidPage(
  fluidRow(
    column(10,visNetworkOutput("network", height = "100%"),
           verbatimTextOutput("test")),
    column(2, actionButton("goButton", "Go!"))
  )
  
)

shinyApp(ui = ui, server = server)
````

**Comment by bthieurmel** [comment]
And, more generally, it seems that sending data from R to javascript taking some time... I'll have a look after hollidays on this.

**Comment by Tixierae** [comment]
Thank you very much, that's interesting. I'll have a close look at that since I am building a shiny app. Have nice holidays.

**Comment by bthieurmel** [comment]
Some another idea....? using ````igraph```` also to set coordinnate : 

````
set.seed(1234)
# create random graph with 140 nodes and 250 edges
g = erdos.renyi.game(140,250,type="gnm")
V(g)$id = 1:140
g_data_frame = get.data.frame(g, what="both")
nodes <- data.frame(g_data_frame$vertices, layout_nicely(g))
colnames(nodes)[2:3] <- c("x", "y")
visNetwork(nodes, g_data_frame$edges) %>% visPhysics(maxVelocity = 25, minVelocity = 20)
````

**Comment by Tixierae** [comment]
Thanks for the suggestion I'm going to try that tomorrow...

**Comment by bthieurmel** [comment]
It's better example : 
````
set.seed(1234)
# create random graph with 140 nodes and 250 edges
g = erdos.renyi.game(140,250,type="gnm")
V(g)$id = 1:140
g_data_frame = get.data.frame(g, what="both")

nodes <- data.frame(id = g_data_frame$vertices, layout_nicely(g)*100)
colnames(nodes)[2:3] <- c("x", "y")

visNetwork(nodes, g_data_frame$edges) %>% 
  visNodes(size = 20, fixed = TRUE) %>% 
  visPhysics(stabilization= FALSE)  %>%
  visOptions(highlightNearest = T, nodesIdSelection = T)
````

I'll think about add a new function to use igraph layout before plotting in the next week, and then can render network quickly. I've just have to check and code the coordinnate transformation from igrah to vis.js canvas.

**Comment by Tixierae** [comment]
The increase in speed is impressive. It goes from ~40 seconds to less than a second. This is great. Making it some default strategy would be highly beneficial I think.

**Comment by bthieurmel** [comment]
I've just initialize and push on gitub a new function ``visIgraphLayout`` to compute coordinates before rendering. So we can now render the network really quicky, and use all igraph layout such as ``layout_in_circle``, ...

**Comment by Tixierae** [comment]
This is awesome! Thanks
