### ISSUE TITLE
[Enhancement] Sorting of "Select by group" dropdown when group labels are numbers

### ISSUE THREAD

**Issue by Tixierae** [DataKnowledge/visNetwork#35]
In the "Les miserables" [example](http://dataknowledge.github.io/visNetwork/options.html), when expanding the "Select by group" dropdown, the levels are not sorted in increasing or decreasing order (e.g., 10 is between 1 and 2). Would it be possible to detect (or let the user specify) when group labels are numbers and provide adequate sorting?

**Comment by bthieurmel** [comment]
Fix. Now, numeric/integer are sorted as number, and character/factor are sorted as character.
Thanks

**Comment by Tixierae** [comment]
Thanks!
