### ISSUE TITLE
Slow loading for dense graph

### ISSUE THREAD

**Issue by michaellevy** [DataKnowledge/visNetwork#37]
I have a very dense, weighted-edges graph (~600 edges, 40 nodes) that takes about 20 seconds to load. It's not stabilization that's slow, nothing appears in that time. Any ideas for how to speed it up? Here's my code:

```
visNetwork(dfs$vertices, dfs$edges) %>%
    visEdges(arrows = 'to',
             color = list(opacity = .3, highlight = 'black'))  %>%
    visNodes(shape = "square",
             color = list(border  = 'black'),
             font = list(size = 28),
             shadow = TRUE) %>%
    visOptions(highlightNearest = TRUE
               , nodesIdSelection = TRUE) %>%
    visPhysics(maxVelocity = 500
               , solver = 'barnesHut'
               , barnesHut = list(gravitationalConstant = -5e3, damping = .6)
    )
```

**Comment by Tixierae** [comment]
You can have a look at the suggestions provided in this [thread](https://github.com/DataKnowledge/visNetwork/issues/32). They were helpful in my case.

**Comment by michaellevy** [comment]
Thanks @Tixierae! 

@bthieurmel: My graph loads very quickly with `smooth = FALSE`, but that destroys the formatting... nodes and labels appear much larger with `smooth = FALSE`. Just FYI.

Thanks for the great package!

**Comment by bthieurmel** [comment]
For information, I've just initialize and push on gitub a new function ``visIgraphLayout`` to compute coordinates before rendering. So we can now render the network really quicky, and use all igraph layout such as ``layout_in_circle``, ...

**Comment by timelyportfolio** [comment]
:100: this is really great!
