### ISSUE TITLE
[Enhancement] Download graph as .pdf or .svg file?

### ISSUE THREAD

**Issue by Tixierae** [DataKnowledge/visNetwork#38]
That would be a nice feature...

**Comment by ThoDuyNguyen** [comment]
As I remember, there was already  a feature to save the network to image file.
Also there was an example when the author export network to html file.  

I think you could use those as a work around in the mean time. :+1:

**Comment by Tixierae** [comment]
Where?

**Comment by ThoDuyNguyen** [comment]
https://github.com/DataKnowledge/visNetwork/issues/30

This link above contains demo code for usage in a Shiny application. If you want to use it in your RStudio only, just search for htmlwidgets::saveWidget in help.

**Comment by bthieurmel** [comment]
Yes, you can actually save the network as .html. Save as png/pdf is in reflexion for the next features.

**Comment by Tixierae** [comment]
Thanks both of you! This is great.

**Comment by bthieurmel** [comment]
Hi,
There is now a simple function ````visSave```` for export as .html, and a new function ````visExport```` to save network as png/jpeg. ````visExport```` only work in shiny application or in a browser.

**Comment by Tixierae** [comment]
Many thanks this is great

**Comment by skanskan** [comment]
Then, how can we export the network to svg or a vectorial pdf from Rstudio?

**Comment by Tixierae** [comment]
You can also use the base R PDF device to plot the igraph

**Comment by skanskan** [comment]
But I would like to have a visnetwork "looking" not a oldfashioned igraph looking.

**Comment by Tixierae** [comment]
If you just want a still picture, forget about visnetwork and just work with igraph. Plotting with igraph doesn't have to be old fashioned. There are many parameters that you can tune in to obtain exactly what you want. See for instance: http://kateto.net/netscix2016

**Comment by skanskan** [comment]
The advantage of visnetwork is that you can place the nodes manually where you want.

**Comment by bthieurmel** [comment]
You can export the network in ``jpg``, ``png`` and ``pdf`` using ``visExport`` function.

This function add a button, and you can click to export the current view of the network. It's working well on ``shiny``. In ``RStudio``, you just have to click before on ``show in new windows`` to open the network in a browser.

**Comment by skanskan** [comment]
OK, I'll try
Does that pdf contain a vectorial graphic or just a raster picture embedded?
