### ISSUE TITLE
optionally add bootstrap?

### ISSUE THREAD

**Issue by timelyportfolio** [DataKnowledge/visNetwork#4]
I understand why you would include Bootstrap to offer an opinionated way of insuring the output looks nice, but it is quite heavy especially when doing `standalone` without the benefit of a CDN.  Also, Bootstrap is not namespaced well, so I have had quite a few conflicts with things such as tooltips when using multiple js libraries.  Would it be better to optionally add/remove Bootstrap?

For reference, I did something like [this](https://github.com/timelyportfolio/navr/blob/master/R/add_navr.R#L13-L30) to add the dependency for FontAwesome.

Another way I have achieved Bootstrap is leveraging `shiny.tags`, since [Shiny has Bootstrap](https://github.com/rstudio/shiny/tree/master/inst/www/shared).

**Comment by bthieurmel** [comment]
I think I use bootstrap only due to the legend option I experiment (very quickly), for divide page into two "network", one for legend, and main network.
So the best thing is perhaps to remove bootstrap, and divide page by other, more simple code ?

**Comment by bthieurmel** [comment]
I think about completely remove boostrap in next version, when also updating to vis.js 4.0, just after a few days of rest ! I'll we ok, I hope, for beginning of June.

**Comment by bthieurmel** [comment]
No bootstrap in current branch visjs_0.4.0 (futur master branch, still some work to do...)
