### ISSUE TITLE
graph redraws for every click when nodes have coordinates, highlightNearest==TRUE and randomSeed is used

### ISSUE THREAD

**Issue by Tixierae** [DataKnowledge/visNetwork#40]
Reproducible example:
````
nodes = data.frame(id=1:10,group=c(rep(1,5),rep(2,5)))
# assign coordinates
nodes[c("x","y")] = layout_nicely(g)*100
edges = data.frame(from=sample(1:10,20,replace=TRUE),to=sample(1:10,20,replace=TRUE))
visNetwork(nodes, edges) %>% visOptions(selectedBy = "group", highlightNearest = TRUE) %>% visLayout(randomSeed = 1234)
````
Clicking on a node (or anywhere on or outside the graph), or selecting a group from the dropdown redraws the graph from scratch (which creates of lot of instability!). The problem is solved when removing `visLayout(randomSeed = 1234)`, but in some cases it might be needed to set seed.

**Comment by Tixierae** [comment]
.html file that shows the issue:

[bug1.zip](https://github.com/DataKnowledge/visNetwork/files/87134/bug1.zip)

**Comment by bthieurmel** [comment]
I've normally solved this yesterday. Check with the good version like in another issue (I don't know why but you use visNetwork_0.1.2 rather the new 0.2.1....)
