### ISSUE TITLE
Add support for basic R color palettes

### ISSUE THREAD

**Issue by Tixierae** [DataKnowledge/visNetwork#43]
Minimal reproducible example:
````
gg = erdos.renyi.game(6,3,type="gnm")
V(gg)$id = 1:6
V(gg)$color = gray.colors(n=6)
gg_data_frame = get.data.frame(gg, what="both")
visNetwork(gg_data_frame$vertices, gg_data_frame$edges)
````
The colors render well for `gray.colors`, but not for any other [standard R color palettes](https://stat.ethz.ch/R-manual/R-devel/library/grDevices/html/palettes.html): `rainbow`, `heat.colors`, etc (in these cases the nodes all show up as black).

**Comment by bthieurmel** [comment]
css color need to be, in hexadecimal format, with 6 digits.

````gray.colors```` is 6 digits color, but some other are in 8 digit (with transparency). You can remove the two last character if you want to use this type of function/colors : 

````
gg = erdos.renyi.game(6,3,type="gnm")
V(gg)$id = 1:6
V(gg)$color = substring(rainbow(n=6), 1, 7)
gg_data_frame = get.data.frame(gg, what="both")
visNetwork(gg_data_frame$vertices, gg_data_frame$edges)
````

**Comment by Tixierae** [comment]
Perfect. Thanks for the prompt and detailed answer.
