### ISSUE TITLE
Use information from the nodes data set to set up legend colors

### ISSUE THREAD

**Issue by Tixierae** [DataKnowledge/visNetwork#44]
Minimal reproducible example:

````
gg = erdos.renyi.game(6,3,type="gnm")
V(gg)$id = 1:6
V(gg)$group = c(1,1,2,2,3,3)
palette = gray.colors(n=3)
V(gg)$color = c(rep(palette[1],2),rep(palette[2],2),rep(palette[3],2))
gg_data_frame = get.data.frame(gg, what="both")
visNetwork(gg_data_frame$vertices, gg_data_frame$edges)  %>% visLegend()
````
Issue: the legend colors are unrelated to the colors used in the graph.

When there are many groups or when executing a dynamic script, it is not always easy or possible to manually add a single `visGroups` statement indicating the color that should be used for each group. Furthermore, this information is already available in the nodes data frame:

````
> gg_data_frame$vertices
  id group   color
1  1     1 #4D4D4D
2  2     1 #4D4D4D
3  3     2 #AEAEAE
4  4     2 #AEAEAE
5  5     3 #E6E6E6
6  6     3 #E6E6E6
````
So that would be nice if the legend colors could match by default the colors assigned to the groups in the nodes data frame.

**Comment by bthieurmel** [comment]
Default is only based on group information, because you can have global options per groups and customization per nodes.

I think if you can set colors in your data.frame, you can also set colors with ````visGroups````, like this for example : 

````
gg = erdos.renyi.game(6,3,type="gnm")
V(gg)$id = 1:6
V(gg)$group = c(1,1,2,2,3,3)
palette = gray.colors(n=3)
# V(gg)$color = c(rep(palette[1],2),rep(palette[2],2),rep(palette[3],2))
gg_data_frame = get.data.frame(gg, what="both")

vis <- visNetwork(gg_data_frame$vertices, gg_data_frame$edges)  %>% visLegend()

set_color <- sapply(1:3, function(x){
  vis <<- vis %>% visGroups(groupname = as.character(x), color = palette[x])
  invisible(NULL)
})

vis
````

Morevover, you pass less data to Javascript like this. 

It's also possible to definie your legend manually....

**Comment by Tixierae** [comment]
Very smart. Thank you very much for all the help...
