### ISSUE TITLE
visIgraphLayout overrides visLayout(randomSeed = 1)

### ISSUE THREAD

**Issue by martinjhnhadley** [DataKnowledge/visNetwork#47]
The newly updated `visIgraphLayout` option is impressively fast - `visNetwork` is now an unrivalled package!

However, I cannot now fix the layout seed. As a MWE I've taken the example from the `visIgraphLayout` documentation page:

```r
nnodes <- 200
nnedges <- 400
nodes <- data.frame(id = 1:nnodes)
edges <- data.frame(from = sample(1:nnodes, nnedges, replace = T),
                    to = sample(1:nnodes, nnedges, replace = T))
visNetwork(nodes, edges) %>%
  visLayout(randomSeed = 1) %>%
  visIgraphLayout() %>%
  visNodes(size = 10)
```

**Comment by bthieurmel** [comment]
Hi,
````visLayout randomSeed```` is internal of ``vis.js`` when we decided to use their coordinates computation algorithm. So there is no effect with ``visIgraphLayout``, which is another algorithm...!
I'll think about add a ``randomSeed``, if possible, to ``visIgraphLayout``

**Comment by martinjhnhadley** [comment]
Cheers, I didn't really expect the ultra naive approach of `visLayout(randomSeed=123)` to work. It would've been better for me to have phrased this as a feature request.

Thanks again for the great package!

**Comment by bthieurmel** [comment]
Done now on 0.2.2 github version, adding ``randomSeed`` to ``visIgraphLayout`` and ``visIgraph``
