### ISSUE TITLE
Does it support to plot network based on using the object from R package igraph

### ISSUE THREAD

**Issue by wenbostar** [DataKnowledge/visNetwork#5]
Hi,
The package visNetwork is a really very cool tool for visualization of network.  Does it support to plot network based on using the object from R package igraph?
Best regards!
Bo

**Comment by timelyportfolio** [comment]
I was thinking the same thing.  @bthieurmel can help correct me here, but here is how I would I start to achieve `igraph` + `visNetwork`.

```
library(igraph)
library(visNetwork)


graph.famous("Walther") %>%
  get.data.frame( what = "both" ) %>%
  {
    visNetwork(
      nodes = data.frame(
        id = unique( c( .[["edges"]][,"from"], .[["edges"]][,"to"] ) )
      )
      ,edges = .[["edges"]]
    )
  }
```

**Comment by timelyportfolio** [comment]
I saved here as a live example http://bl.ocks.org/timelyportfolio/109a4dabf671cc37f201.

**Comment by bthieurmel** [comment]
Hi,
I was thinking the same thing to, but don't yet have time to look at the question.
I think add igraph-visNetwork functionnalities in futur is a good thing. 
Can also perhaps think about use igraph to calculate coordinnate, before plot with vis.js in case a lot of data.

**Comment by timelyportfolio** [comment]
Just as an update with the new functionality introduced today (see https://github.com/DataKnowledge/visNetwork/issues/32)

```
library(igraph)
library(visNetwork)


graph.famous("Walther") %>%
    get.data.frame( what = "both" ) %>%
    {
        visNetwork(
            nodes = data.frame(
                id = unique( c( .[["edges"]][,"from"], .[["edges"]][,"to"] ) )
            )
            ,edges = .[["edges"]]
        )
    } %>%
    visIgraphLayout(layout = "layout.fruchterman.reingold", physics = TRUE, smooth = TRUE) %>%
    visOptions(highlightNearest = TRUE)
```

**Comment by bthieurmel** [comment]
By the way, I've just initialize a (little bit experimental) function ``visIgraph`` to render an ``igraph`` object in ``visNetwork``. So you can now do : 

````
igraph_network <- graph.famous("Walther")
visIgraph(igraph_network)

g <- graph.full(5)
E(g)$weight <- runif(ecount(g))
E(g)$width <- 1
E(g)$color <- "red"
E(g)[ weight < 0.5 ]$width <- 4
E(g)[ weight < 0.5 ]$color <- "green"
visIgraph(g)
````
Try to keep some information from igraph to visNetwork (color, size, label), but I think there is a lot of features to add. (I don't know ``igraph`` very well...!)
