### ISSUE TITLE
Nodes belongs to multiple groups

### ISSUE THREAD

**Issue by kmezhoud** [DataKnowledge/visNetwork#53]
Hi,
I am trying to set network with nodes that can be part of multiple groups, or create subgroups.
I used visGroups
Not working...
Any suggestions?
Thanks

```
nodes <- data.frame(id = 1:10, 
                    label = paste("Node", 1:10),
                    value = c(10,5,3,7,2,3,2.6,2,9,2),
                    shape ="circle",
                    group= c("Gr1","Gr3")
                    )   

edges <- data.frame(from = sample(1:10,8), to = sample(1:10, 8)) 

graph <- visNetwork(nodes, edges, width = "150%")
visNetwork(nodes, edges, width = "150%") 
 visNodes(graph, scaling = list(label = list(enabled = TRUE)), group= list(group = list(enabled= TRUE)))
  visGroups(graph, useDefaultGroups = TRUE, groupname = c("BB1","BB3"))
   visOptions(graph,manipulation = TRUE, selectedBy = "group")

```

**Comment by bthieurmel** [comment]
It's actually only possible to assign a node to one group. An issue #31 for an enhancement already exists. It is on my road map in a near future.

**Comment by bthieurmel** [comment]
Hi,

Now possible with a new argument ``multiple = TRUE``, and using comma separated values in one column : 

````
nodes <- data.frame(id = 1:15, label = paste("Label", 1:15),
                    group = sample(LETTERS[1:3], 15, replace = TRUE), stringsAsFactors = F)

edges <- data.frame(from = trunc(runif(15)*(15-1))+1,
                    to = trunc(runif(15)*(15-1))+1)

# and with multiple groups ?
nodes$group <- sample(c("group 1", "group 2", "group 1, group 2, group 3"), nrow(nodes), replace = TRUE)
visNetwork(nodes, edges) %>% 
  visOptions(selectedBy = list(variable = "group", multiple = TRUE))
````

**Comment by kmezhoud** [comment]
Great,
I will try it.
Thanks,
Karim

**Comment by amorigoye** [comment]
Hi please kindly help me with this, I'm practicing with visNetwork to 
create data visualization as with the sample configuration below;
library(visNetwork)
nodes<-data.frame(id=1:14,
edges<-data.frame(from =c(1,1,2,3,3,3,2,7,7,7,2,11,11,11,11),
 to =c(2,3,4,5,6,7,8,9,10,11,12,13,14))
visNetwork(nodes, edges, width="100%")
What I want to do is that nodes {11,12,13,14} will have yellow color, 
and nodes {7,8,9,10} in blue color and nodes {3,4,5,6} will also have green color.
 Please kindly guide me how to go about this. 
Thank you very much as I wait to hear from you.
