### ISSUE TITLE
Dynamically change edge "color" based on egde "value?

### ISSUE THREAD

**Issue by dcosgrov** [DataKnowledge/visNetwork#55]
I am currently attempting to build a "network weathermap" using your incredible visNetwork package (thanks for all of your hard work on this!), but am struggling to find a way to dynamically change the edge color based on a "value" for the edge (i.e. traffic volume between nodes drives edge color ).

Here is a link to a specific network weathermap image that I am essentially trying to build dynamically based on values read from a database:

http://network-weathermap.com/manual/0.97b/howto.png

Thanks for any guidance that you can provide,

Dave

**Comment by bthieurmel** [comment]
HI, 
What do you heard about "dynamically" ?

Having the value, you can set color for edges using the ``color`` column and some R transformation from numeric to color : 

````
# minimal example
nodes <- data.frame(id = 1:3)
edges <- data.frame(from = c(1,2), to = c(1,3), value = c(1:2))

edges$color <- palette()[edges$value]

visNetwork(nodes, edges)
````

**Comment by bthieurmel** [comment]
For some dynamically change with ``shiny``, you can now have a look to new features ``visUpdateNodes`` and ``visUpdateEdges``. Related to #50

**Comment by dcosgrov** [comment]
bthieurmel,

Thanks for the great suggestions - I plan to try these out this weekend, and I will let you know my results. 

Dave

**Comment by dcosgrov** [comment]
bthieurmel,

Your suggestion worked perfectly.  I just tweaked  slightly to utilize the 7 rainbow colors that typically are used in a network weathermap.  Thanks for your assistance!

nodes <- data.frame(id = 1:8, label=paste("Node",1:8)) 
edges <- data.frame(from = c(1,1,1,1,1,1,1),
                    to = c(2,3,4,5,6,7,8),
                    value = c(1,2,3,4,5,6,7))

edges$color <- palette(rainbow(7))[edges$value]

visNetwork(nodes, edges)
