### ISSUE TITLE
navigationButtons = TRUE doesn't work properly!

### ISSUE THREAD

**Issue by Morais14** [DataKnowledge/visNetwork#57]
In my webbrowser the navigation button doesn't work. If i press an arrow the network goes to that direction infinitely so if i press another arrow the network stops and all navigation controls too. This happens in this example https://cran.r-project.org/web/packages/visNetwork/vignettes/Introduction-to-visNetwork.html . In this example http://visjs.org/examples/network/other/navigation.html they works properly. 

Any tips?

**Comment by bthieurmel** [comment]
Yes, it seems this is a bug of the vis.js library 4.12.0, which is the version of the CRAN R package I think. (https://github.com/almende/vis/blob/master/HISTORY.md)
You can install the github version, and it'll be ok.

**Comment by Morais14** [comment]
Thanks a lot! Works like a charm!!
