### ISSUE TITLE
Is it applicable to get zoomed and focused on selected node (from "select by id" drop down list)?

### ISSUE THREAD

**Issue by ThoDuyNguyen** [DataKnowledge/visNetwork#60]
Currently, when I select an ID from "Select by id" drop down list, the node gets highlight. 
Could I make the node get zoomed and focus also with the action? 
The demo comes with code for get focus by another observer drop down list box and I think it is better not to add another selectInput.

Thank you in advance.

**Comment by bthieurmel** [comment]
Whe you use ``nodesIdSelection`` in shiny, a input is created with the value of the current id. So you can use it in a ``observer``, like this for example : 

````
require(visNetwork)
require(shiny)

server = function(input, output) {
  
  output$network <- renderVisNetwork({
    nodes <- data.frame(id = 1:3)
    edges <- data.frame(from = c(1,2), to = c(1,3))
    
    visNetwork(nodes, edges) %>% visOptions(nodesIdSelection = T, highlightNearest = T)
  })
  
  output$nodesIdSelection_value <- renderPrint({
    input$network_selected
  })
  
  observe({
    id <- input$network_selected
    if(!is.null(id)){
      if(id != ""){
        visNetworkProxy("network") %>% visFocus(id = id) 
      }else{
        # reset zoom
        visNetworkProxy("network") %>% visFit(nodes = NULL)
      }
    }
  })
}



ui = fluidPage(
 visNetworkOutput("network"),
 verbatimTextOutput("nodesIdSelection_value")
)

shinyApp(ui = ui, server = server)
````

**Comment by ThoDuyNguyen** [comment]
Thank you for your reply, this is what I need to implement. 
Is there any official document for type of input$network_selected? 
This feature is great and I look deep into the proxy feature.

**Comment by ThoDuyNguyen** [comment]
I notice that in your example the exported graph will lost the focus feature. 
I suppose the listener/observer is on server side only (so it is only in Shiny application)?

**Comment by bthieurmel** [comment]
You have this information on website (http://dataknowledge.github.io/visNetwork/shiny.html) and in the shiny application demo ``shiny::runApp(system.file("shiny", package = "visNetwork"))``.

If you use ``visExport`` in shiny, you'll keep the focus. Perhaps with a html export using ``visSave``, you lost the feature because the graph is initialized each time you open the file

**Comment by ThoDuyNguyen** [comment]
Thank you for all.
