### ISSUE TITLE
performance on larger networks

### ISSUE THREAD

**Issue by FrissAnalytics** [DataKnowledge/visNetwork#7]
Hi,

thanks for a great package! great work! 

the visjs.org website has a performance example (see http://visjs.org/examples/network/exampleApplications/worldCupPerformance.html) showing a relatively large network, which renders just fine.

When running experiments in Shiny with a matrix of 1000 nodes and 1000 edges the performance unfortunately becomes quite slow, even in chrome with a CORE i7 processor. Is there any known reason for this? Could it have to do with the fact that visjs.org currently offers version 4.0, while your current shiny implementation is based on version 3.12.0?

kind regards, Herman

**Comment by bthieurmel** [comment]
Hi,
Actually, I don't know if vis.js 4.0 have better performance than vis.js 3.12.0. I'll try to start the package update today.

Can you put all the options used in WorldCup example ?

````
physics: {
        stabilization: false,
        barnesHut: {
          gravitationalConstant: -80000,
          springConstant: 0.001,
          springLength: 200
        }
      },
      interaction: {
        tooltipDelay: 200,
        hideEdgesOnDrag: true
      }
````

In particular, use  ````visOptions(stabilize = FALSE)```` is very usefull for display quite large network, with and without shiny, for begin displaying network before any stabilization algorithm.

**Comment by FrissAnalytics** [comment]
you were absolutely right, it was the physics setting which needed to be adjusted. After a bit of toying around with the WorldCup example settings you suggested all my bigger networks rendered just fine! Thanks!!!
